export enum AsyncDataStateEnum {
    INITIALISE= "INITIALISE",
    STARTED = "STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED_SUCCESS = "COMPLETED_SUCCESS",
    COMPLETED_FAIL = "COMPLETED_FAIL",
}